### This notebook contains code that's meant to showcase and introduce the learner to Numpy and some of its basic operations.

In [2]:
import numpy as np

In [4]:
# create an array by passing in a list of lists
ratings = np.array([[94, 89, 63, 45], [93, 92, 48, 23], [92, 94, 56, 98]])

In [7]:
# inspecting the shape of the array
ratings.shape

(3, 4)

In [9]:
# Create an array of ones - pass in shape as a tuple
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# Create an array of zeros - pass in shape as a tuple
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Create an array of random values - pass in shape as a tuple
np.random.random((3, 3))

array([[0.70428129, 0.31295573, 0.34414917],
       [0.08544296, 0.49969193, 0.27663565],
       [0.48320787, 0.18055346, 0.58964538]])

### Accessing NumPy arrays

In [16]:
ratings

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98]])

In [18]:
# selecting the top left element
ratings[0, 0]

np.int64(94)

In [21]:
# Selecting the first row
ratings[0, :]

array([94, 89, 63, 45])

In [23]:
# Select the first column
ratings[:, 0]

array([94, 93, 92])

In [25]:
# Select the first two rows and first two columns
ratings[0:2, 0:2]

array([[94, 89],
       [93, 92]])

#### Boolean Array Indexing

In [27]:
# Select all values greater than 90
ratings[ratings > 90]

array([94, 93, 92, 92, 94, 98])

### Modifying NumPy arrays

In [31]:
# Append an extra row
ratings_extra_row = np.append(ratings, [[92, 88, 78, 55]], axis=0)

ratings_extra_row

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98],
       [92, 88, 78, 55]])

In [32]:
ratings

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98]])

In [34]:
# Delete the 3rd row
ratings_del_row = np.delete(ratings, [2], axis=0)

ratings_del_row

array([[94, 89, 63, 45],
       [93, 92, 48, 23]])

### Functions on NumPy arrays

In [37]:
# Sum of all elements in the array
ratings.sum()

np.int64(887)

In [39]:
# Sum of each row
ratings.sum(axis=1)

array([291, 256, 340])

In [41]:
# Sum of each column
ratings.sum(axis=0)

array([279, 275, 167, 166])

In [43]:
# Min of each row
ratings.min(axis=1)

array([45, 23, 56])

In [45]:
# Finds the index of the maximum value in the entire array
overall_max_index = np.argmax(ratings)

overall_max_index

np.int64(11)