### This notebook contains code that's meant to help the learner explore the fundamentals of NumPy for efficient data manipulation and analysis

In [2]:
import numpy as np

#### Exercise One: Given a 2D NumPy array, pollution_data, represnting daily air quality index values of a city for a week (rows for days and columns for different pollutants), write a code snippet to return the day (row) with the highest average pollution level

In [4]:
pollution_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])

In [7]:
max_avg_pollution_level_per_day = np.argmax(pollution_data, axis=1)

print(max_avg_pollution_level_per_day)

[2 1 2]


#### Exercise Two: A forest department is monitoring deforestation by analysing satellite data of five similarly sized regions. When the monitoring started, each region had full forest coverage (i.e. 100). The most recent data collected has been stored in a 1D NumPy array, forest_coverage, where each element represents the percentage of forest cover in different regions. Write code to calculate the total percentage of coverage lost, if each 1% reduction in forest cover equals 100 square kilometers.

In [9]:
forest_coverage = np.array([70, 80, 65, 90, 85])

In [17]:
pct_loss_per_region = 100 - forest_coverage

print(f" The percentage loss per region is: {pct_loss_per_region}")

 The percentage loss per region is: [30 20 35 10 15]


In [18]:
sqr_area_per_region_lost = 100 * pct_loss_per_region

print(f"The square kilometers lost per region are: {sqr_area_per_region_lost}")

The square kilometers lost per region are: [3000 2000 3500 1000 1500]


#### Exercise 3: For a study on water conservation, we have a 2D NumPy array, water_quality, representing different water quality parameters (columns) for various water bodies (rows). Write code to find the water body index (row index) with the worst average quality parameter.

In [20]:
water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])

In [22]:
min_avg_quality_param_per_row = np.argmin(water_quality, axis=1)

print(min_avg_quality_param_per_row)

[1 0]


#### Exercise Four: Biologists tracking caracal movement have recorded the number of caracals spotted in different regions in a 2D NumPy array, animal_sightings. Each row represents a different region, and columns represent different days. Write a code snippet to find the index of the region with the highest average number of sightings.

In [24]:
animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

In [28]:
row_averages = animal_sightings.mean(axis=1)

highest_avg_num_sightings = row_averages.argmax()

print(highest_avg_num_sightings)

2


#### Exercise Five: Biologists have collected data on bird sightings in a region over a month, stored in a 1D NumPy array where each element represents the number of sightings on a particular day. Reshape this data into a 2D array (matrix) representing weeks and days (assume 4 weeks in a month, 7 days per week), and calculate the total sightings for each week.

In [36]:
bird_sightings = np.array([3,4,2,5,1,0,4,3,5,2,1,7,8,1,2,3,4,1,0,5,6,2,3,4,1,4,6,7])

bird_sightings_reshape = bird_sightings.reshape(4, 7)

print(bird_sightings_reshape)

total_sightings_per_week = bird_sightings_reshape.sum(axis=1)

print(f"Total sightings per week are: {total_sightings_per_week}")

[[3 4 2 5 1 0 4]
 [3 5 2 1 7 8 1]
 [2 3 4 1 0 5 6]
 [2 3 4 1 4 6 7]]
Total sightings per week are: [19 27 21 27]


In [32]:
bird_sightings_reshape.shape

(4, 7)

#### Exercise Six: Meteorologists have recorded temperature and precipitation data over a year in a 2D array (rows for months, columns for temperature and precipitation). Transpose the array so that rows represent temperature and precipitation, and columns represent months. Then calculate the average temperature and precipitation over the year

In [34]:
climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

In [38]:
climate_data_transposed = climate_data.transpose()

print(climate_data_transposed)

average_temperature = climate_data_transposed[0].mean()
average_precipitation = climate_data_transposed[1].mean()

print(f"The average temperature is: {average_temperature}")
print(f"The average precipitation is: {average_precipitation}")

[[22 25 28 30 27 25 23 24 24 22 20 18 22]
 [50 43 35 20 25 30 40 55 55 60 65 70 58]]
The average temperature is: 23.846153846153847
The average precipitation is: 46.61538461538461
