In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [62]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
population_df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,57715.0,58055.0,58386.0,58726.0,...,101353.0,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0
AFG,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,10152331.0,10372630.0,10604346.0,10854428.0,...,27294031.0,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0
AGO,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,6309770.0,6414995.0,6523791.0,6642632.0,...,21759420.0,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0
ALB,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,2022272.0,2081695.0,...,2947314.0,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0
AND,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,19647.0,20758.0,21890.0,23058.0,...,83861.0,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0


In [18]:
population_df.describe().T

,count,mean,std,min,25%,50%,75%,max
1960,214.0,1.408851e+07,5.767208e+07,4279.0,237035.00,2401711.0,8045923.50,6.670700e+08
1961,214.0,1.427893e+07,5.775221e+07,4453.0,238495.25,2442783.5,8189191.50,6.603300e+08
1962,214.0,1.452514e+07,5.848146e+07,4566.0,241677.00,2492448.0,8280730.00,6.657700e+08
1963,214.0,1.482807e+07,5.980582e+07,4656.0,247233.00,2537329.5,8390127.00,6.823350e+08
1964,214.0,1.513290e+07,6.111311e+07,4748.0,253358.00,2585682.5,8508820.25,6.983550e+08
1965,214.0,1.544440e+07,6.247168e+07,4841.0,260197.00,2630378.0,8615307.75,7.151850e+08
1966,214.0,1.577058e+07,6.401060e+07,4936.0,267900.00,2679029.5,8778726.75,7.354000e+08
1967,214.0,1.609526e+07,6.550343e+07,5033.0,276326.50,2740750.0,8929183.00,7.545500e+08
1968,214.0,1.642355e+07,6.704857e+07,5161.0,284974.50,2797295.0,9110254.50,7.745100e+08
1969,214.0,1.677135e+07,6.870634e+07,5303.0,292655.50,2863830.5,9324390.50,7.960250e+08


### Challenge 1: Population Growth

In [167]:
def get_population_growth_rate_by_country_year(df, country_code):
    country_series = df.loc[country_code]
    
    # create an empty list to store the results
    results = []
    
    for i in range(1, len(country_series)):
        prev_pop = country_series.iloc[i - 1]
        curr_pop = country_series.iloc[i]
        
        year = country_series.index[i]
        
        growth_rate = (curr_pop - prev_pop) / prev_pop
        
        results.append([
            float(year),
            round(growth_rate, 5)
        ])
    
    return np.array(results)

In [168]:
get_population_growth_rate_by_country_year(population_df, 'ABW')

array([[ 1.961e+03,  2.263e-02],
       [ 1.962e+03,  1.420e-02],
       [ 1.963e+03,  8.360e-03],
       [ 1.964e+03,  5.940e-03],
       [ 1.965e+03,  5.750e-03],
       [ 1.966e+03,  6.190e-03],
       [ 1.967e+03,  5.890e-03],
       [ 1.968e+03,  5.700e-03],
       [ 1.969e+03,  5.820e-03],
       [ 1.970e+03,  5.740e-03],
       [ 1.971e+03,  6.380e-03],
       [ 1.972e+03,  6.730e-03],
       [ 1.973e+03,  6.730e-03],
       [ 1.974e+03,  4.730e-03],
       [ 1.975e+03,  2.130e-03],
       [ 1.976e+03, -1.170e-03],
       [ 1.977e+03, -3.630e-03],
       [ 1.978e+03, -4.360e-03],
       [ 1.979e+03, -2.050e-03],
       [ 1.980e+03,  1.930e-03],
       [ 1.981e+03,  7.840e-03],
       [ 1.982e+03,  1.285e-02],
       [ 1.983e+03,  1.395e-02],
       [ 1.984e+03,  1.021e-02],
       [ 1.985e+03,  3.020e-03],
       [ 1.986e+03, -6.060e-03],
       [ 1.987e+03, -1.295e-02],
       [ 1.988e+03, -1.219e-02],
       [ 1.989e+03, -7.700e-04],
       [ 1.990e+03,  1.830e-02],
       [ 1

### Challenge 2: Even-odd train-test split

In [171]:
def feature_response_split(arr):
    X = arr[:, 0]
    y = arr[:, 1]
    
    # split masks
    even_mask = X % 2 == 0
    
    X_train = X[even_mask]
    X_test = X[~even_mask]
    y_train = y[even_mask]
    y_test = y[~even_mask]
    
    return (X_train, y_train), (X_test, y_test)

In [172]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), (X_test, y_test) = feature_response_split(data)

In [166]:
y_train

array([ 0.0142 ,  0.00594,  0.00619,  0.0057 ,  0.00574,  0.00673,
        0.00473, -0.00117, -0.00436,  0.00193,  0.01285,  0.01021,
       -0.00606, -0.01219,  0.0183 ,  0.05591,  0.05787,  0.0358 ,
        0.02137,  0.02076,  0.02254,  0.01773,  0.00801,  0.00131,
        0.00213,  0.00513,  0.00589,  0.00461])

### Challenge 3: Fitting a Model using sklearn's `DecisionTreeRegressor`

In [119]:
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

In [164]:
def train_model(X_train, y_train, MaxDepth):
    X_train = X_train.reshape(-1,1)
    
    tree = DecisionTreeRegressor(max_depth=MaxDepth, random_state=42)
    tree.fit(X_train, y_train)
    
    return tree

In [113]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), _ = feature_response_split(data)

train_model(X_train, y_train, 3).predict([[2017]])

array([0.00451333])

### Challenge 4: Now we would like to test our model on the testing data that we produced in Exercise 2. This test will give the Root Mean Squared Logarithmic Error (RMSLE)

In [165]:
from sklearn.metrics import mean_squared_log_error

In [159]:
def test_model(model, y_test, X_test):
    X_test = X_test.reshape(-1, 1)
    y_pred = model.predict(X_test)
    
    y_pred = np.clip(y_pred, 0, None)
    y_test = np.clip(y_test, 0, None)
    
    rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred))
    
    return float(round(rmsle, 3))

In [160]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), (X_test, y_test) = feature_response_split(data)

lm = train_model(X_train, y_train, 3)
test_model(lm, y_test, X_test)

0.007